"""Port interfaces (Protocols) for infrastructure adapters.

Domain depends on these protocols. Infrastructure implements them.
"""

from __future__ import annotations

from typing import Protocol, Optional, Literal, runtime_checkable

from codegraph.domain.models import Symbol, Edge, Chunk, SymbolKind, EdgeKind
from codegraph.domain.workspace import (
    WorkspaceState, IndexMetadata, FileManifestEntry,
    FileDiagnostic, PackageRoot,
)


@runtime_checkable
class SymbolStore(Protocol):
    """Persistence port for symbols, edges, chunks, and metadata."""

    def get_symbol(self, symbol_id: str) -> Optional[Symbol]: ...
    def get_symbol_by_key(self, symbol_key: str) -> Optional[Symbol]: ...
    def query_symbols(
        self,
        file_path: Optional[str] = None,
        kind: Optional[SymbolKind] = None,
        name_pattern: Optional[str] = None,
        max_results: int = 200,
        cursor: Optional[str] = None,
    ) -> tuple[list[Symbol], Optional[str]]: ...
    def upsert_symbols(self, symbols: list[Symbol]) -> None: ...
    def delete_symbols_by_file(self, file_path: str) -> None: ...

    def get_edges(
        self,
        source_id: Optional[str] = None,
        target_id: Optional[str] = None,
        kind: Optional[EdgeKind] = None,
        file_path: Optional[str] = None,
        max_results: int = 200,
        cursor: Optional[str] = None,
    ) -> tuple[list[Edge], Optional[str]]: ...
    def upsert_edges(self, edges: list[Edge]) -> None: ...
    def delete_edges_by_file(self, file_path: str) -> None: ...

    def get_chunks(
        self,
        file_path: Optional[str] = None,
        has_vector: Optional[bool] = None,
        max_results: int = 200,
    ) -> list[Chunk]: ...
    def upsert_chunks(self, chunks: list[Chunk]) -> None: ...
    def delete_chunks_by_file(self, file_path: str) -> None: ...
    def vector_search(
        self,
        query_vector: list[float],
        top_k: int = 10,
        path_prefix: Optional[str] = None,
        language: Optional[str] = None,
        symbol_kind: Optional[str] = None,
        exclude_tests: bool = False,
        file_filter: Optional[str] = None,
    ) -> list[Chunk]: ...

    def get_metadata(self) -> Optional[IndexMetadata]: ...
    def set_metadata(self, metadata: IndexMetadata) -> None: ...

    def get_diagnostics(self) -> list[FileDiagnostic]: ...
    def set_diagnostics(self, diagnostics: list[FileDiagnostic]) -> None: ...

    def compact(self, keep_generations: int = 3) -> dict: ...
    def close(self) -> None: ...


@runtime_checkable
class EmbeddingProvider(Protocol):
    """Port for embedding providers (local ONNX, OpenAI, Voyage, custom)."""

    name: str = ...
    dimension: int = ...
    max_tokens: int = ...
    normalize: Literal["none", "l2"] = ...
    supports_dimension_override: bool = ...
    supports_batch: bool = ...
    max_batch_tokens: Optional[int] = ...

    async def embed_batch(self, texts: list[str]) -> list[list[float]]: ...
    async def embed_single(self, text: str) -> list[float]: ...
    def estimate_tokens(self, text: str) -> Optional[int]: ...


@runtime_checkable
class GitClient(Protocol):
    """Port for git operations."""

    def get_head_commit(self) -> Optional[str]: ...
    def get_changed_files_since(self, base_ref: str, head_ref: str = "HEAD", include_worktree: bool = True) -> list[dict]: ...
    def get_untracked_files(self) -> list[str]: ...
    def get_staged_files(self) -> list[str]: ...
    def get_status_porcelain(self) -> str: ...
    def get_diff_name_status(self, base_ref: str, head_ref: str = "HEAD", detect_renames: bool = True) -> list[dict]: ...
    def get_git_head_mtime(self) -> Optional[float]: ...
    def get_git_index_mtime(self) -> Optional[float]: ...
    def is_git_repo(self) -> bool: ...
    def get_default_branch(self) -> Optional[str]: ...
    def is_dirty(self) -> bool: ...
    def get_diff_unified(self, file_path: str, base_ref: Optional[str] = None, head_ref: Optional[str] = None, context_lines: int = 3) -> Optional[str]: ...


@runtime_checkable
class CodeParser(Protocol):
    """Port for language-specific code parsing (tree-sitter)."""

    def parse_file(self, file_path: str, content: str, language: str) -> tuple[list[Symbol], list[Edge], list[FileDiagnostic]]: ...
    def available_languages(self) -> list[dict]: ...
    def detect_language(self, file_path: str) -> Optional[str]: ...


@runtime_checkable
class ImportResolver(Protocol):
    """Port for cross-file import resolution."""

    def resolve_imports(
        self,
        edges: list[Edge],
        symbols: dict[str, Symbol],
        package_roots: list[PackageRoot],
    ) -> list[Edge]: ...


class FileWatcher(Protocol):
    """Port for filesystem event watching."""

    def start(self, paths: list[str], callback: callable) -> None: ...
    def stop(self) -> None: ...
    def is_available(self) -> bool: ...
